default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "password" %>
  pool: 5

development:
  <<: *default
  database: shop_easy_bd_development

test:
  <<: *default
  database: shop_easy_bd_test

production:
  <<: *default
  database: shop_easy_bd_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV["DATABASE_HOST"] || "db" %>
